spring:
  application:
    name: friendexam

  datasource:
    url: jdbc:mysql://localhost:3306/database01
    username: illa0308
    password: orange9801!
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 80
